### ISSUE TITLE
NetherPortal glitch

### ISSUE THREAD

**Issue by ErikderFreak** [Scommander/ExplosionRebuilderDatapack#10]
-Bug: Glitched Netherportal and no item drops from player. 
-How it happened: Go through nether portal and have a creeper explode on the other side as soon as passing through.
-NOTE: It happend on an older version. But I didn't find a bug fix in the patchnotes for it, so I thought it might still be in there. 
-How it looks: (Dirt block placed by hand after)
![grafik](https://user-images.githubusercontent.com/38981373/154732588-bcb535d9-4d37-4585-9ded-8d7b948578c0.png)

**Comment by ErikderFreak** [comment]
Update on this. It still happens in the 2.0 Version. 
I believe it is because the area gets unloaded when the player dies before all the portal blocks are rebuild.

**Comment by Scommander** [comment]
I'll see if I can add a check to ensure the chunk is loaded, I think you're most likely right @ErikderFreak.

**Comment by Scommander** [comment]
I believe I have found a fix which will be implemented in the 1.20.1 release very soon! Happy days!
