### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by ghost** [Scommander/ExplosionRebuilderDatapack#5]
recreate:
have creeper blown up chest
chest drop item inside of it
chest get replaced by the datapack with all the item it has dropped
item inside the chest gets duplicated
suggested solution:
program all storage block to get rebuilt without NBT

**Comment by Scommander** [comment]
Could you provide a video example of this duplication in a new issue? I am unable to reproduce this - I believe the datapack already handles this case?
